@NEXT_PUBLIC_API_BASE={{$dotenv NEXT_PUBLIC_API_BASE}}
###todo|  tecnico puede ver sus tickets:
GET {{NEXT_PUBLIC_API_BASE}}/ticketsporTecnico/66d411494deb5f20bc732cf9

###   {
###     "tickets": [
###       {
###         "_id": "66d40f28d6c24ac2d232b852",
###         "descripcion": "tiket de Scarlett a Pepe 1",
###         "tecnico": "66d381bbe1105cd285a8ab72",
###         "cliente": "66d3fffa96affc9038360e00",
###         "estado": "Pendiente"
###       },
###       ...
###     ]
###   }

###todo|  Registrar técnico
POST {{NEXT_PUBLIC_API_BASE}}/registroTecnico
content-type: application/json

{
  "nombre": "Melany",
  "apellido": "Polo",
  "cedula": 124567891,
  "fecha_nacimiento": "1991-01-01",
  "genero": "Femenino",
  "ciudad": "Quito",
  "direccion": "Calle 13 #45-67",
  "telefono": 3001234007,
  "email": "melany@ejemplo.com",
  "password": "contraseña123",
  "token": null,
  "tickets": []
}

###   {
###     "msg": "Tecnico registrado"
###   }


###todo|  Login del técnico
POST {{NEXT_PUBLIC_API_BASE}}/login
content-type: application/json

{
  "email": "melany@ejemplo.com",
  "password": "contraseña123"
}
###   {
###     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDFlZjEyNmUyOGY2ODE0YmJkNTc3OSIsInJvbCI6InRlY25pY28iLCJpYXQiOjE3MjUxMzc0MzgsImV4cCI6MTcyNTIyMzgzOH0.hOW90O0YUq870rlEoelHRUH88X4kl1lVpU1LMPs3uVc",
###     "nombre": "Juan",
###     "apellido": "Pérez",
###     "direccion": "Calle 123 #45-67",
###     "telefono": 3001234567,
###     "_id": "66d1ef126e28f6814bbd5779",
###     "email": "juan.perez@ejemplo.com",
###     "rol": "tecnico"
###   }

###todo|  obtener un técnico en específico
GET {{NEXT_PUBLIC_API_BASE}}/descripcionTecnico/66d411494deb5f20bc732cf9
###   {
###     "_id": "66d1ef126e28f6814bbd5779",
###     "nombre": "Juan",
###     "apellido": "Pérez",
###     "cedula": 1234567890,
###     "fecha_nacimiento": "1990-01-01",
###     "genero": "Masculino",
###     "ciudad": "Bogotá",
###     "direccion": "Calle 123 #45-67",
###     "telefono": 3001234567,
###     "email": "juan.perez@ejemplo.com",
###     "password": "$2a$10$upb5/cyFhi25TnU5nk0rdu/cC0M5X.DVgJKG0PT01boFWrPL5W86m",
###     "token": "x01s4f56lmt",
###     "tickets": [],
###     "__v": 0
###   }
