# usuario: david - técnico: juan

###?  cliente registra un tícket:
POST http://localhost:3001/api/ticket/registro
content-type: application/json

{
  "codigo":12349,
  "descripcion": "ticket abierto 1",
  "técnico": "66d1ef126e28f6814bbd5779",
  "cliente": "66d373bdcaa2334b8e429449",
  "respuesta": " "
}
###   {
###     "msg": "Ticket registrado"
###   }

###todo|  técnico responde el tiket de un usuario (id del ticket):
POST http://localhost:3001/api/ticketRespuesta/66d37b8ee1105cd285a8ab57
content-type: application/json

{
  "respuesta": "estimado, su respuesta al ticket 1"
}
###    {
###      "msg": "Respuesta guardada"
###    }

###? detalle del ticket individual (id del ticket):
GET http://localhost:3001/api/ticket/66d37b8ee1105cd285a8ab57

###   {
###     "_id": "66d37b8ee1105cd285a8ab57",
###     "codigo": 12347,
###     "descripcion": "ticket abierto",
###     "cliente": "66d373bdcaa2334b8e429449",
###     "estado": "Pendiente",
###     "respuesta": "estimado, su respuesta al ticket 1",
###     "__v": 0
###   }

###?  cliente actualiza ticket 
put http://localhost:3001/api/actualizarTicket/66d37b8ee1105cd285a8ab57
###?  cliente elimina ticket 
put http://localhost:3001/api/eliminarTicket/66d37b8ee1105cd285a8ab57
###todo|  técnico actualiza ticket 
put http://localhost:3001/api/estadoTicket/66d37b8ee1105cd285a8ab57
