@NEXT_PUBLIC_API_BASE={{$dotenv NEXT_PUBLIC_API_BASE}}

###todo|  cliente puede ver todos los técnicos ✅
GET {{NEXT_PUBLIC_API_BASE}}/listarTecnicos

###   [
###     {
###       "_id": "66d1ef126e28f6814bbd5779",
###       "nombre": "Juan",
###       "genero": "Masculino",
###       "email": "juan.perez@ejemplo.com"
###     },
###     ...
###   ]

###? cliente registra un tícket: ✅
POST {{NEXT_PUBLIC_API_BASE}}/ticket/registro
content-type: application/json

{
  "descripcion": "tiket de Scarlett a Juan 3",
  "tecnico": "66d411494deb5f20bc732cf9",
  "cliente": "66d411d84deb5f20bc732cff",
  "respuesta": " "
}
###   {
###     "msg": "Ticket registrado"
###   }

###todo|  técnico responde el tiket de un usuario (id del ticket):
POST {{NEXT_PUBLIC_API_BASE}}/ticketRespuesta/66d412284deb5f20bc732d04
content-type: application/json

{
  "respuesta": "Holaaaaaaaaaaaa"
}
### RESPONSE OK:
###    {
###      "msg": "Respuesta guardada"
###    }

###? (AMBOS) detalle del ticket individual (id del ticket):
GET {{NEXT_PUBLIC_API_BASE}}/ticket/66d412284deb5f20bc732d04

###   {
###     "_id": "66d4012996affc9038360e07",
###     "descripcion": "ticket abierto",
###     "cliente": "66d373bdcaa2334b8e429449",
###     "estado": "Pendiente",
###     "respuesta": "estimado, su respuesta al ticket 1",
###     "__v": 0
###   }

###?  cliente actualiza ticket id:ticket
PUT {{NEXT_PUBLIC_API_BASE}}/actualizarTicket/66d412284deb5f20bc732d04
content-type: application/json

{
  "descripcion": "tiket de Pepe Narvaez a Melany Polo 2"
}

###   {
###     "msg": "Actualización exitosa del ticket"
###   }

###?  cliente elimina ticket 
DELETE {{NEXT_PUBLIC_API_BASE}}/eliminarTicket/66d40fc9e1620a55dc87af2b

###   {
###     "msg": "Ticket eliminado exitosamente"
###   }

###todo|  técnico cambia el estado del ticket
POST {{NEXT_PUBLIC_API_BASE}}/estadoTicket/66d412284deb5f20bc732d04
content-type: application/json

{
  "estado":"Finalizado"
}

###  {
###    "msg": "Estado del ticket modificado exitosamente"
###  }
